name: Log group
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "::groups::Show environment variables"
                printenv
                echo "::endgroup::"